### ISSUE TITLE
the native app won't compile if one of the dependencies is a typescript project

### ISSUE THREAD

**Issue by ghost** [NathanWalker/nativescript-ng2-magic#12]
Hello,
first of all, thanks for this awesome tool! I'm working on integrating nativescript rendering into an existing nativescript/angular2 project, and this fits exactly my needs.
I have juste one problem : I can see that the main nativescript code is compiled into javascript in the nativescript folder, but, I have some typescripts projects in my dependencies, and because of that, the native app crashes when trying to parse a typescript file in tns_modules.

JS ERROR SyntaxError: Unexpected keyword 'import'.

For what I understand, when running tns emulate, the typescript cli takes the main typescript/angular2 project, compiles the js files, and gets rid of the ts files, but how can I make it work on the dependencies as well?

Thank you!

**Comment by NathanWalker** [comment]
Hi @roma98 thanks!

Sorry to hear about the issue you're having. Hmm, I haven't seen this. It sounds like you may be using a somewhat off beat setup, no?

**Comment by NathanWalker** [comment]
However to make it work on the dependencies, if you place them inside the `nativescript/app` folder, it should process them just the same, however you may need to import your libs based on that location changes since you would not be going through the standard node_modules folder.

**Comment by ghost** [comment]
Thank your for getting back to me!
I made some progress on this issue and would like to know what you think of it:
The problem lays on the nativescript-dev-typescript hookup.
When I type `tns prepare` , the `node_modules` folder is created.
Then for what I understand, the hookup takes care of compiling every `.ts` file into a `.js` file, but then when launching the native app, it crashed when trying to read a `.ts` file with a `JS ERROR Syntax Error`.

I don't want to waste your time if this issue is not related to the module you developed, but I have just 2 questions :
- is it suppose to be a problem if the tns_module folder on the native app has `.ts` files in it?
- I've used `npm - i nativescript-ng2-magic` on an existing project created from `https://github.com/AngularClass/angular2-webpack-starter`, I know it's not one of the supported project, but when installing the module, it seems to work fine so I've decided to give it a go :-) Are there any types of dependencies that could have gone wrong by using this project?

Thanks again!

**Comment by ghost** [comment]
I was thinking about writing my own modified hookup for `nativescript-dev-typescript`... I order to compile the `.ts` files, and get rid of them to keep only the `.js` files.
I also had the same type of problem with `nativecsript-dev-sass`, the `.scss` files are compiled into `.css` files, but since the `.scss` files stays, I also get a parsing error on it during execution of the app

**Comment by ghost** [comment]
I found out my configuration wasn't right, thanks for your time!

**Comment by NathanWalker** [comment]
Oh! excellent to hear, please let me know if you run into anything else!

**Comment by tjvantoll** [comment]
@roma98: By chance do you remember what your configuration problem was? I’m hitting the exact same error and I’m trying to figure out what’s going on.

**Comment by ghost** [comment]
@tjvantoll : Sorry mate I've moved to another project since then, and we gave up on nativescript since our configuration was too much customized.
Good luck!
