### ISSUE TITLE
Module not found: Error: Can't resolve './app/app.component.html' when running ng serve

### ISSUE THREAD

**Issue by iguissouma** [NathanWalker/nativescript-ng2-magic#14]
I have an issue using `nativescript-ng2-magic` when running web module with absolute path in app.component.ts 

```
@Component({
  selector: 'app-root',
  templateUrl: './app/app.component.html',
  styleUrls: ['./app/app.component.css']
})
```

the error:

```
[1] ERROR in ./src/app/app.component.ts
[1] Module not found: Error: Can't resolve './app/app.component.html' in '/Users/iguissouma/IdeaProjects/native-angular-apollo/src/app'
[1]  @ ./src/app/app.component.ts 42:22-57
[1]  @ ./src/app/index.ts
[1]  @ ./src/main.ts
[1]  @ multi main
[1] 
[1] ERROR in ./src/app/app.component.ts
[1] Module not found: Error: Can't resolve './app/app.component.css' in '/Users/iguissouma/IdeaProjects/native-angular-apollo/src/app'
[1]  @ ./src/app/app.component.ts 43:21-55
[1]  @ ./src/app/index.ts
[1]  @ ./src/main.ts
[1]  @ multi main
[1] Child html-webpack-plugin for "index.html":
[1]          Asset     Size  Chunks       Chunk Names
[1]     index.html  2.82 kB       0       
[1] webpack: bundle is now VALID.
```

The web module works fine when I use relative path:

```
@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css']
})
```

or

```
@Component({
  selector: 'app-root',
  templateUrl: '../app/app.component.html',
  styleUrls: ['../app/app.component.css']
})
```

The mobile app works only with absolute path, do you have an idea about this error in a project generated with angular-cli generate with the latest version.

```
angular-cli: 1.0.0-beta.15
node: 4.4.3
os: darwin x64

```

**Comment by NathanWalker** [comment]
Hi @iguissouma webpack integration is new with angular-cli so I believe that may have introduced some of this. However I was able to make it work by ensuring I use the `Component` from ng2-magic as mentioned [here](https://github.com/NathanWalker/nativescript-ng2-magic#example).

And then making sure the comonent does not use `moduleId: module.id`.
The `templateUrl` should be a full relative path as mentioned also in the readme.

**Comment by iguissouma** [comment]
Hello @NathanWalker, 
Thanks for this information.  

Could you take a look what I'm missing here in this repository [native-angular-apollo](https://github.com/iguissouma/native-angular-apollo)

**Comment by iguissouma** [comment]
It seems that angular-cli will compile only with valid path relative to src/app.
As a workaround to get both web and mobile working I modified magic.service.js as below:

```
MagicService.TEMPLATE_URL = function (path) {
        if (MagicService.IS_NATIVESCRIPT()) {
            path = path.replace("./", "./app/");
            var paths = path.split('.');
            paths.splice(-1);
            return paths.join('.') + ".tns.html";
        }
        else {
            return path;
        }
    };
```

In my app.component.ts

```
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
```

**Comment by NathanWalker** [comment]
@iguissouma `1.8.2` includes your modification, thanks for that 👍 
Also works with latest cli, latest {N}+angular supporting TypeScript 2.0 and you can have `.tns.css` files now too for custom {N} styling.

**Comment by AyWa** [comment]
@NathanWalker 
I have the opposite issue when I am running 
`npm run start.android`
this one will work

```
import { Component } from 'nativescript-ng2-magic';
import { OnInit } from '@angular/core';
@Component({
  selector: 'app-topbar',
  templateUrl: 'app/topbar/topbar.component.html'
})
```

while this one will not work

```
import { Component } from 'nativescript-ng2-magic';
import { OnInit } from '@angular/core';
@Component({
  selector: 'app-topbar',
  templateUrl: './topbar.component.html'
})
```

But I think it is only related to NativeScript. Did you encounter the same issue ? 
I am using:

```
nativescript-ng2-magic": "1.8.2
nativescript-angular": "1.1.2
angular-cli": "1.0.0-beta.15
```

**Comment by iguissouma** [comment]
Can you try this and see if it works?

```
import { Component } from 'nativescript-ng2-magic';
import { OnInit } from '@angular/core';
@Component({
  selector: 'app-topbar',
  templateUrl: './topbar/topbar.component.html'
})
```

**Comment by NathanWalker** [comment]
Can you try just this:
```
import { Component } from 'nativescript-ng2-magic';
import { OnInit } from '@angular/core';
@Component({
  selector: 'app-topbar',
  templateUrl: 'topbar.component.html'
})
```

**Comment by NathanWalker** [comment]
@iguissouma I just verified the following works with angular-cli `v1.0.0-beta.19-3`, the latest:

```
import { Component } from 'nativescript-ng2-magic';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app works!';
}
```

You will need to of course create `app.component.tns.html` and `app.component.tns.css`.

**Comment by AyWa** [comment]
Hi,
@iguissouma your solution work for nativescript but then ng build/ng serve will not find the html and throw an error.
@NathanWalker my AppComponent/rootcomponent is same as you and working but my others component are not working with ./name.component.html & css. while it is working with angular-cli.

**Comment by LeoLazGR** [comment]
I have a similar problem with nativescript-ng2-magic version 1.9.0:

In my starting component (app.component.*) (path: app/app/) I have included page-router-outlet to be redirected to the login page. For this, I have declared the path in app.routing.ts 
`{path: "", redirectTo: "/login"}.`

The files for the login page are under app/components/login. in login.routing I declared the path 
`{ path: "login", component: LoginComponent }`. 
Then I am doing a RouterModule.forChild(loginRoutes);

The login component (same path as the login.routing.ts) looks like this:

```
@Component({
  selector: "login",
  templateUrl: "./login.component.html",
  styleUrls: ["./login.common.css"],
})
export class LoginComponent implements OnInit {
 ...
}
```

The web-app works fine. When I want to start the mobile app I got the error message:

Error: File /data/data/org.nativescript.nativescript/files/app/app/login.component.tns.html does not exist.

That's right. As I wrote above the file is under app/app/components/login. Why is nativscript-ng2-magic looking in the wrong path?

If I am using 

```
@Component({
  selector: "login",
  templateUrl: "./components/login/login.component.html",
  styleUrls: ["./components/login/login.common.css"],
})
export class LoginComponent implements OnInit {
 ...
}

the mobile app works, but then the Web-App doesn't work any more because the files are not found 
```

**Comment by himanshu331** [comment]
Hi NathanWalker,
I have the same problem as the LeoLazGR have.. can you plz give me the solution, how to solve this error as mentioned above. and i am using full absolute path like: Home/abc/project/src/app/app.component does not exist.

**Comment by rhanb** [comment]
This plugin doesn't work with absolute paths in subfolders, you should use paths as follow:

```typescript
@Component({
  selector: "login",
  moduleId: module.id,
  templateUrl: "login.component.html",
  styleUrls: ["login.common.css"],
})
```

**Comment by NathanWalker** [comment]
Thanks you @rhanbIT that is correct - at the moment, `moduleId` and just the filename is what is supported.
Eventually this project will provide a webpack loader which will auto copy the appropriate templates into the {N} folder and remove the need for the custom decorator. I'm hoping for that by end of April at least.

**Comment by aldo-roman** [comment]
@NathanWalker  any update on this? I'm hitting this error while runnig `tns run android`.

This does not reproduce when using `npm run start-android-bundle`, but that command does not support livesync, so it is very difficult to develop.

Thanks!

**Comment by eman264** [comment]
cd : Cannot find path 'C:\Users\work pc\OneDrive\Desktop\FrontEnd\WorkSpace\my-dream-app' because it does not exist.
At line:1 char:1
+ cd my-dream-app
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\work p...ce\my-dream-app:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

**Comment by Monteiro-Rafael** [comment]
> This plugin doesn't work with absolute paths in subfolders, you should use paths as follow:
> 
> ```ts
> @Component({
>   selector: "login",
>   moduleId: module.id,
>   templateUrl: "login.component.html",
>   styleUrls: ["login.common.css"],
> })
> ```

Thank you! @rhanb that worked for me too
