### ISSUE TITLE
app.component.sass does not exist: Nativescript Angular compilation error

### ISSUE THREAD

**Issue by rhanb** [NathanWalker/nativescript-ng2-magic#16]
Hi,

I'm using nativescript-ng2-magic on a angular-cli generated project with the option --style=sass. 
As the issue [#14](https://github.com/NathanWalker/nativescript-ng2-magic/issues/14) i had the same problem, and i fixed it as [iguissouma](https://github.com/iguissouma) by changing magic.service.js. 

But i also have the same issue for the style either in css or sass, i checked in the nativescript app source and the file does exist.
The global style.sass modifications works on browser but not in NativeScript.

the error:

```
File /data/data/org.nativescript.nativescript/files/app/app.component.sass does not exist. Resolved from: app.component.sass.

Error: File /data/data/org.nativescript.nativescript/files/app/app.component.sass does not exist. Resolved from: app.component.sass.
    at FileSystemResourceLoader.get (/data/data/org.nativescript.nativescript/files/app/tns_modules/nativescript-angular/resource-loader.js:22:19)
    at DirectiveNormalizer._fetch (/data/data/org.nativescript.nativescript/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js:13443:45)
    at /data/data/org.nativescript.nativescript/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js:13543:55
    at Array.map (native)
    at DirectiveNormalizer._loadMissingExternalStylesheets (/data/data/org.nativescript.nativescript/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js:13543:16)
    at DirectiveNormalizer.normalizeExternalStylesheets (/data/data/org.nativescript.nativescript/files/app/tns_modules/@angular/compiler/bundle
```

I tried this way too:

```
@Component({
  selector: 'app-root',
  moduleId: module.id,
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.sass']
})
```

In NativeScript it works, which is great, but in browser i have the following error:

```
ncaught Error: moduleId should be a string in "AppComponent". See https://goo.gl/wIDDiL for more information.
If you're using Webpack you should inline the template and the styles, see https://goo.gl/X2J8zc.componentModuleUrl @ metadata_resolver.js:700CompileMetadataResolver.getDirectiveMetadata @ metadata_resolver.js:144(anonymous function) @ metadata_resolver.js:268CompileMetadataResolver.getNgModuleMetadata @ metadata_resolver.js:262RuntimeCompiler._compileComponents @ runtime_compiler.js:130RuntimeCompiler._compileModuleAndComponents @ runtime_compiler.js:68RuntimeCompiler.compileModuleAsync @ runtime_compiler.js:59PlatformRef_._bootstrapModuleWithZone @ application_ref.js:302PlatformRef_.bootstrapModule @ application_ref.js:284(anonymous function) @ main.ts:12__webpack_require__ @ bootstrap 7aa65cf…:52(anonymous function) @ zone.js:1327__webpack_require__ @ bootstrap 7aa65cf…:52webpackJsonpCallback @ bootstrap 7aa65cf…:23(anonymous function) @ main.bundle.js:1
```

I think it comes from angular-cli which uses webpack 

Since it is the same type of error as the template problem, i checked the code source and i saw that the module doesnt take care in consideration the styles files. 
So i modified it as follow (in the root node_modules folder and in the nativescript > node_modules folder):

magic.service.js

```
 MagicService.STYLE_URLS = function (pathArray) {
    if (MagicService.IS_NATIVESCRIPT()) {
      var currentPath;
      for (var i = 0; i < pathArray.length; i++) {
        console.log(currentPath);
        currentPath = pathArray[i];
        currentPath = currentPath.replace("./", "./app/");
        var paths = currentPath.split('.');
        paths.splice(-1);
        currentPath = paths.join('.') + ".tns.sass";
        pathArray[i] = currentPath;
        console.error(pathArray[i]);
      }
      console.error('STYLE_URLS', pathArray);
      return pathArray;
    }
    else {
      return path;
    }
  };
```

magic.service.d.ts:

```
export declare class MagicService {
    static TEMPLATE_URL(path: string): string;
    static STYLES_URL(stylesPath: string): string;
    static IS_NATIVESCRIPT(): boolean;
}
```

utils.js:

```
 MagicDecoratorUtils.getMetadata = function (metadata, customDecoratorMetadata) {
        if (metadata === void 0) { metadata = {}; }
        if (metadata.templateUrl) {
            // correct view for platform target
            metadata.templateUrl = magic_service_1.MagicService.TEMPLATE_URL(metadata.templateUrl);
        }
        if (metadata.styleUrls) {
          metadata.styleUrls = magic_service_1.MagicService.STYLES_URL(metadata.styleUrls);
        }
        return metadata;
    };
```

With this method, it does work even if NativeScript does not support sass onload, it will work with css (changes to the code are needed: ".sass" .. ".css") 

If you have a way to make it work without all those modifications it would be great :D

PS: Yes it needs a little refactoring, first step, make it work ;)

**Comment by rhanb** [comment]
In midtime i created a new package:

[nativescript-ng2-cli-magic](https://www.npmjs.com/package/nativescript-ng2-cli-magic)

Which i modified for angular-cli generated projects, i also added a function to handle styleUrls (only css, since nativescript doesn't support sass in styleUrls).

If you want to update your package to make it work for the last version of angular-cli, i will delete the package :)

**Comment by NathanWalker** [comment]
Nice work @rhanbIT. I will make updates this week to allow this.

However, `SASS` is supported in NativeScript via this plugin:
https://github.com/toddanglin/nativescript-dev-sass

Once you install that, `scss` files will auto-compile when running your {N} app and the `.css` files specified in your component `styleUrls` will just work.

**Comment by rhanb** [comment]
Cool thanks! :)

Oh, nice ! i was using `sass --watch` but on command is always better than two ! 

Could you give me a shoutout when you will have update the package?

**Comment by NathanWalker** [comment]
@rhanbIT `1.8.2` has all the goods now including compatibility with latest {N}+angular using TypeScript 2.0 👍
