### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by sandeepgosavi** [NathanWalker/nativescript-ng2-magic#18]
Hi, Can you please share a code implementing page routing for web app and mobile app

**Comment by HachimDev** [comment]
Yes i also need one please
for me, page-router-outlet doesn't work in my app.component.tns.html
please check my post on stackOverFlow 
http://stackoverflow.com/questions/41057885/page-router-outlet-not-working-in-my-nativescript-ng2-magic-project

**Comment by NathanWalker** [comment]
@sandeepgosavi If you have not found this already, you may look here:
https://github.com/jlooper/pocketrave

**Comment by sandeepgosavi** [comment]
I have created my own project without referencing anyone. [Here is git link](https://github.com/sandeepgosavi/HelloAngular) for it. It is helpful for those who are very new to {N}

**Comment by NathanWalker** [comment]
Very nice @sandeepgosavi thank you!
