### ISSUE TITLE
folder don't get created in the nativescript/app when creating them in the src/app

### ISSUE THREAD

**Issue by HachimDev** [NathanWalker/nativescript-ng2-magic#19]
hey, my project didn't get updated when I changed the folding in my src/app directory.
I added 2 folders but they didn't show up in my nativescript/app/app folder as it should be. 
the page2 folder was added and deleted after
any idea how to fix it please ?
![ns folder](https://cloud.githubusercontent.com/assets/20968869/21153948/97fe803a-c164-11e6-8b27-8d6775c25e1b.png)
![src folder](https://cloud.githubusercontent.com/assets/20968869/21153946/96c23e00-c164-11e6-9819-91f410a9f7f3.jpg)

**Comment by NathanWalker** [comment]
@HachimDev you can try running this manually from root of your web project:

```
node ./node_modules/nativescript-ng2-magic/install.js
```

That will queue up the post installer again to attempt to create the symlink again.

**Comment by HachimDev** [comment]
Thanks @NathanWalker here is what It said :
```
We were unable to create a symlink  - from -
   E:\Angular 2 NativeScript\ng2-Magicc3\ng2-Magicc\src\client     - to -
   E:\Angular 2 NativeScript\ng2-Magicc3\ng2-Magicc\nativescript\app\client
If you don't create this symlink, you will have to manually copy the code each time you change it.
```
after going to the install.js, I saw that the seeds var is always equal to "client" so maybe seedId is always equal to 1. maybe it's the problem since i don't have any src\client folder in my project

**Comment by NathanWalker** [comment]
Fixed here, note new repo and install:
https://github.com/wwwalkerrun/nativescript-ngx-magic

**Comment by HachimDev** [comment]
Alright ! Thanks
