### ISSUE TITLE
No provider for Location

### ISSUE THREAD

**Issue by LiorArbel** [NathanWalker/nativescript-ng2-magic#22]
On a fresh angular-cli project, after you get everything to work, if you use `Location` from `@angular/common` the bootstrap will fail with the message 'No provider for Location!` which doesn't happen on a regular angular-cli web app.

Thanks In advance.

**Comment by LiorArbel** [comment]
Closed because this is probably a by-product of #23

**Comment by NathanWalker** [comment]
Fixed here, note new repo and install:
https://github.com/wwwalkerrun/nativescript-ngx-magic
