### ISSUE TITLE
Advice for existing angular 2 app using webpack

### ISSUE THREAD

**Issue by jlutz777** [NathanWalker/nativescript-ng2-magic#26]
I have an existing angular 2 app that uses webpack (so it has a fairly involved webpack config). This project is the closest thing I've found to giving advice on setting up an existing project with nativescript, but I'm getting tripped up on webpack.

I tried following the steps here as well (http://docs.nativescript.org/tooling/bundling-with-webpack), but that seemed to create a new webpack config.

Any advice on steps to follow?

**Comment by NathanWalker** [comment]
You will want to install the {N} Webpack plugin in the nativescript folder only since that is not to be used in the Root of the project which Angular cli uses.

**Comment by jlutz777** [comment]
When it comes to the webpack configuration that I already have that is also needed for NativeScript, I'm guessing there is no easy path. Do you basically have to just take the generated nativescript/webpack.common.js and update it appropriately to match the existing one?

On a related note, is the separate "nativescript" folder with symbolic links necessary for existing projects? I know that's how this particular project works, but I was just wondering about the whole symbolic link need.

I appreciate the advice and looking forward to getting my project working with NativeScript!

**Comment by NathanWalker** [comment]
Please note new repo and install:
https://github.com/wwwalkerrun/nativescript-ngx-magic
