### ISSUE TITLE
install failed due to nativescript-angular version bump not published

### ISSUE THREAD

**Issue by dvh91** [NathanWalker/nativescript-ng2-magic#27]
Note that regular install fails due to nativescript-angular version not published (1.4.1)
for a quick workaround- you can fork 'template-hello-world-ng' repo.
change the nativescript-angular version back to 1.3.0
then change the install.js in nativescript-ng2-magic to pull from your fork of 'template-hello-world-ng'.
and run install.js again.

hope it helps someone.

**Comment by NathanWalker** [comment]
Fixed here, note new repo and install:
https://github.com/wwwalkerrun/nativescript-ngx-magic
