### ISSUE TITLE
Using new @Router disregards ngOnInit

### ISSUE THREAD

**Issue by sushruth** [NathanWalker/nativescript-ng2-magic#8]
When using the `Router` module from `@angular/Router` (for routing in code), the app throws an error 

```
EXCEPTION: Error: Uncaught (in promise): Cannot find default outlet
```

Using `ngOnInit` to run the code below, wont help.

``` js
this.router.navigate(['/auth'])
```

Should I downgrade my Router to RouterConfig and use `useDefault: true` ?

**Comment by NathanWalker** [comment]
Not sure here @sushruth this sounds like an issue related to angular router and not magic lib?
